More Modcomp shit
Foundation-19/Foundation-19 pull request #1112
Opened 2023-04-19 22:19 UTC by cheesePizza2

## About the Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-06-25 18:10 UTC, TheDarkElites commented
Omg no way hes gonna finish mod comps stuff!!!

We stan cheese!!!

2023-07-04 15:56 UTC, TheDarkElites requested changes
Stuff you should fix
Also, you should get Tusurpta to look at this after you fix the things I mentioned since he's a much better maintainer than me.

2023-07-04 15:56 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/programs/servers/upload_database.dm
> +	var/list/datum/computer_file/program/upload_database_c/clients = list()	// all connected clients
Use the auto doc feature for these.
```
/// comment
var/whatever_the_fuck
```

2023-07-04 15:56 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/programs/servers/upload_database.dm
> +	data["regions"] = regions*/
???

2023-07-04 15:56 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/programs/servers/upload_database.dm
> +	//var/obj/item/stock_parts/computer/hard_drive/HDD = computer.hard_drive
more stuff you left commented out

2023-07-04 15:56 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/programs/servers/upload_database_c.dm
> +	var/actual_netspeed = 0									// actual transfer speed (displayed in UI)
Use auto doc here too

2023-07-04 15:56 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/programs/servers/upload_database_c.dm
> +// crashes the client and displays specific error message
Auto doc for the proc defines aswell

2023-07-04 22:46 UTC, TheDarkElites commented
This looks good enough for me, will assign it as waiting for test merge.

2023-07-11 17:13 UTC, TheDarkElites commented
[17:06:33] Runtime in virus.dm, line 154: Cannot read null.access
proc name: process tick (/datum/computer_file/program/virus/process_tick)
src: /datum/computer_file/program/v... (/datum/computer_file/program/virus)
call stack:
/datum/computer_file/program/v... (/datum/computer_file/program/virus): process tick()
the laptop computer (/obj/item/modular_computer/laptop/preset/custom_loadout/advanced): Process(10, 4953, Objs (/datum/controller/subsystem/processing/obj))
Objs (/datum/controller/subsystem/processing/obj): fire(0)
Objs (/datum/controller/subsystem/processing/obj): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

2023-07-14 14:17 UTC, TheDarkElites requested changes

2023-07-14 14:17 UTC, TheDarkElites commented on code/game/movietitles.dm
> +		if(H.get_assignment("NONE", "NONE") != "NONE")
get rid of the global GetAssignment proc all together if you're gonna replace all of the use cases.

2023-07-14 14:44 UTC, TheDarkElites commented on code/game/movietitles.dm
> +		if(H.get_assignment("NONE", "NONE") != "NONE")
nevermind im fucking blind apparently

2023-07-14 14:46 UTC, TheDarkElites requested changes

2023-07-14 14:46 UTC, TheDarkElites commented on code/modules/modular_computers/file_system/reports/crew_record.dm
> +/mob/proc/CreateModularRecord()
move above //Global methods comment since this is now a local proc

2023-07-16 16:42 UTC, cheesePizza2 commented on code/modules/modular_computers/file_system/reports/crew_record.dm
> +/mob/proc/CreateModularRecord()
done (nerd)

2023-07-16 16:52 UTC, TheDarkElites approved these changes
Tsurpta said this is good, it looks good to me, and it passed TM

god bless the modcomp pr

2023-07-16 16:52 UTC, merged