173 AI Rework
Foundation-19/Foundation-19 pull request #1116
Opened 2023-04-21 00:31 UTC by TheDarkElites

## About the Pull Request

Basically, uh 173's AI kinda mid and cant take advantage of 173's new abilities. Also it just teleports behind people so kinda oof.

173 Can now attempt to free itself from its cage
173 No longer just teleports behind people but instead moves towards them (very quickly)
173 Can now properly wander
173 Now remembers targets and can track them through doors
173 Can now pathfind through obstacles he can destroy (windows and doors)
173 Will now attempt to flee when facing more than two humans
173 Will now attempt to break lights when appropriate

uh thats about it

## Why It's Good For The Game

Better AI good (I'm going to make his AI enabled in a later PR even when in low pop and just make it so he cant breach himself and cant be controlled by a human instead of just being catatonic under 30 pop)

Uhhh oh yeah hold on I had something else here

_flips through notes_

yeah, _ahem_, fuck you cheese stay away from my manual email password.

That is all.

## Changelog

:cl:
add: 173 AI now good :)
/:cl:

2023-04-22 16:25 UTC, TheDarkElites commented
time to get yelled at for shitcode :')

2023-04-22 18:28 UTC, Tsurupeta commented
Arguably, teleporting behind is better than attempted pathfinding via walking...

2023-04-22 18:59 UTC, TheDarkElites commented
> Arguably, teleporting behind is better than attempted pathfinding via walking...

No? Only maybe in terms of cost.

A.) Teleporting in the previous system means that if you were in 173's view, his snap cooldown was expired, and you blinked, there was a 100% chance of death. This basically makes 173 incredibly infuriating and incredibly difficult to counter from as no matter what you do if you can't evade him if you're backed into a corner. This way, there is a chance that 173 might not catch up to you or otherwise gives players the ability to evade/outrun him better if they're being smart rather than just luck of whether or not your blink timer runs out or if you can find a door.

B.) This isn't pathfinding via walking. This is pathfinding and then following that path. This is what allows 173 to follow players through objects as it lets him actually break open doors and follow through. Before 173 would basically sit in whatever room he was in while moving very little until someone found him. Then, as long as you closed a door on him, you were fine. Additionally, you cant replicate this pathfinding through obstacles with the previous system unless you're fine with 173 teleporting through doors.

In essence, this encouraged the gameplay loop of "find a door or get out of sight before blink or die". This means in situations where you weren't backed into a corner, its piss easy to escape, but in situations where you are cornered, it's instant death no matter what you do.

This evens out that gameplay loop by first stopping doors from being a be all end all escape route and actually allowing the AI to overcome obstacles (like doors/windows) but also giving people backed into a corner a chance to escape by using blinking as a method to lure 173 away from chokepoints (much like in CB). 

TLDR:

Its a little more expensive, sure, but it majorly improves gameplay against the 173 AI.

PS: We need competent AI that can simulate an experience similar to if a player was controlling them for non-RP hostile SCPs since we are likely to make such SCPs only playable on breach, so in all other cases, the SCPs need to be still able to provide fun and balanced gameplay when only controlled by their AI.

2023-04-22 19:00 UTC, TheDarkElites commented
Also please explain what you mean by "attempted pathfinding"?

2023-04-22 20:12 UTC, TheDarkElites commented
do not TM, fixing issues

2023-04-22 21:06 UTC, TheDarkElites commented
Okay, the issues Tsuru brought up about 173 being easy to doge have been addressed

2023-04-22 22:01 UTC, TheDarkElites commented
ready for TM whenever

2023-04-26 02:47 UTC, ivanmixo requested changes

2023-04-26 02:47 UTC, ivanmixo commented on code/modules/SCP/SCPs/SCP-173.dm
> +	return
Pointless return

2023-04-26 02:47 UTC, ivanmixo commented on code/modules/SCP/SCPs/SCP-173.dm
> +	else
Pointless else

2023-04-26 02:47 UTC, ivanmixo commented on code/modules/SCP/SCPs/SCP-173.dm
> +		if(H.stat == DEAD)
Could prob combine these two into an OR. AStar one can stay separate since it's huge.

2023-04-26 02:47 UTC, ivanmixo commented
Can't believe we don't have an alive human list though. TODO

2023-05-04 17:18 UTC, ivanmixo approved these changes

2023-05-04 17:19 UTC, merged