Changes objectives code slightly/better objectives (dont perma me)
Foundation-19/Foundation-19 pull request #1132
Opened 2023-04-24 20:00 UTC by HaultyAnonie

:cl:
add: RCD to steal objective
code: made code to escape the shuttle to then a train 
/:cl:

2023-04-24 20:36 UTC, Tsurupeta commented
Your code has changed my decision and I'm now in full support of your community ban.

2023-04-24 20:49 UTC, cheesePizza2 reviewed
how do you fuck up this badly on such a small pr lmao

2023-04-24 20:49 UTC, cheesePizza2 commented on code/game/gamemodes/objective.dm
> +datum/objective/rev/find_target_by_role(role, role_type=0)
```suggestion
/datum/objective/rev/find_target_by_role(role, role_type=0)
```
lol, lmao even

2023-04-24 20:49 UTC, cheesePizza2 commented on code/game/gamemodes/objective.dm
> + 	..(role, role_type)
```suggestion
	..(role, role_type)
```
why did you fucking add a space

2023-04-24 20:49 UTC, cheesePizza2 commented on code/game/gamemodes/objective.dm
> + 		explanation_text = "Assassinate, capture or convert [target.current.real_name], the [!role_type ? target.assigned_role : target.special_role]."
```suggestion
		explanation_text = "Assassinate, capture or convert [target.current.real_name], the [!role_type ? target.assigned_role : target.special_role]."
```

2023-04-24 20:49 UTC, cheesePizza2 commented on code/game/gamemodes/objective.dm
> + 	else
```suggestion
	else
```

2023-04-24 21:38 UTC, HaultyAnonie commented on code/game/gamemodes/objective.dm
> + 	else
DO I LOOK LIKE I KNOW

2023-04-24 21:38 UTC, HaultyAnonie commented
> Your code has changed my decision and I'm now in full support of your community ban.

HEY!!!

2023-04-24 22:07 UTC, TheDarkElites commented
This is unironically the funniest shit I have ever seen

2023-04-25 23:58 UTC, checkraisefold commented
what the fuck is this pr

2023-04-26 02:17 UTC, ivanmixo requested changes
proper cl please

2023-04-28 20:40 UTC, HaultyAnonie commented
> proper cl please

fixed... (i hope)

2023-05-03 20:36 UTC, ivanmixo approved these changes

2023-05-03 20:36 UTC, merged