New METAL DETECTORS for LCZ
Foundation-19/Foundation-19 pull request #1146
Opened 2023-05-04 03:19 UTC by cheesePizza2

## About the Pull Request

Technically contraband detectors, but most people call them by the same name.
Mobs (and items, so you can't just throw your backpack across) that pass through are scanned for contraband status, right now it's basically just guns, knives, shards, and tools, but it could be expanded decently easily.
There are some in LCZ by default (blocking off mining, the canteen, and the kitchen), although engineers can easily make more.
Also adds an aluminum box that can pass undetected through said scanner (including the contents inside) so that'll be nice.

Has wires system for fun sabotage gameplay; turn off power, the radio system, or make it think everything is contraband and frame that guy you don't like.

## Why It's Good For The Game

LCZ guards need something to help them control D-class even at lowpop, and D-class need obstacles to push them towards sneakier gameplay.

## Future Improvements

Wiring system looked completely fucked and needs to be fixed sometime. The announcement system that the metal detector uses is _extremely_ unoptimized, and I'll probably fix it up in a separate PR.

## Changelog

:cl:
add: Adds new contraband detectors! Found in LCZ D-block next to mining, and constructable by engineers, these scanners search personnel that walk through it for contraband (guns, tools, knives, etc). There are also ways for clever D-class to bypass or even abuse them (aluminum boxes, hacking, etc).
/:cl:

2023-05-04 16:17 UTC, Tsurupeta requested changes

2023-05-04 16:17 UTC, Tsurupeta commented on code/game/atoms_movable.dm
> +
are you retarded?

2023-05-04 16:17 UTC, aidan-bowman commented on code/game/atoms_movable.dm
> +
????

2023-05-04 16:19 UTC, Tsurupeta commented on code/game/atoms_movable.dm
> +
Move is not Crossed, there's entire proc called CROSSED and also CROSS

2023-05-04 16:37 UTC, cheesePizza2 commented on code/game/atoms_movable.dm
> +
renamed

2023-05-05 11:04 UTC, EgorDinamit commented on code/game/machinery/contraband_detector.dm
> +	var/radio_wire_cut = FALSE				// if cut, removes ability to radio
You have wires for that, why make it into variables?

2023-05-05 11:05 UTC, EgorDinamit commented on code/game/machinery/contraband_detector.dm
> +	if(prob(100 - (severity * 20)))
Maybe qdel at devastation range/severity?

2023-05-05 11:06 UTC, EgorDinamit commented on code/game/machinery/contraband_detector.dm
> +		src.set_broken(TRUE)
src is always implied, you don't have to put it here.

2023-05-05 14:06 UTC, aidan-bowman commented on code/game/machinery/contraband_detector.dm
> +	if(prob(100 - (severity * 20)))
That already happens in the ..()

2023-05-08 12:31 UTC, cheesePizza2 commented
welp wires are broken, i can't fucking figure out why though. will take a look at em later

2023-05-16 19:47 UTC, Tsurupeta commented
I'll TM it

2023-07-11 02:00 UTC, TheDarkElites commented
Ill throw this in for tming tmrw but I'd like for @Tsurupeta to look over it and give his approval before it gets fully merged.

2023-07-11 13:20 UTC, TheDarkElites commented
![image](https://github.com/Foundation-19/Foundation-19/assets/73414180/8e94cb4c-0c0d-452f-a59c-78183c740e31)
this needs a cooldown of some sort

2023-07-11 13:21 UTC, TheDarkElites commented
also please make it so you can jump to the detector from the message

2023-07-13 21:20 UTC, TheDarkElites requested changes
See Comments

2023-07-13 21:20 UTC, TheDarkElites commented on code/game/machinery/contraband_detector.dm
> +/obj/machinery/contraband_detector_construct/attackby(obj/item/I, mob/user)
This should use the /obj/machinery/constructable_frame system as any other machine.

2023-07-13 21:25 UTC, casualspacestation14enjoyer commented
detection system works on borgs, no need to flood the chat more

2023-07-17 12:35 UTC, cheesePizza2 commented on code/game/machinery/contraband_detector.dm
> +/obj/machinery/contraband_detector_construct/attackby(obj/item/I, mob/user)
done

2023-07-17 18:21 UTC, TheDarkElites requested changes

2023-07-17 18:21 UTC, TheDarkElites commented on code/game/machinery/contraband_detector.dm
> +		wrenching = FALSE
This is handled by obj/machinery

If you need to override for checks just do the check and then return ..(args)

2023-07-17 18:21 UTC, TheDarkElites commented on code/game/machinery/contraband_detector.dm
> +		return wires.Interact(user)
Same with this, dont override just do any special checks and use obj/machinery's unarmedAttack override

2023-07-21 17:26 UTC, TheDarkElites approved these changes, later dismissed
Passed TM and it looks good to me.

2023-07-21 20:25 UTC, Tsurupeta commented on code/datums/observation/moved.dm
> +	SEND_SIGNAL(src, COMSIG_EXITED, exitee, new_loc)
We already have this code in `code/datums/observation/entered.dm` and `exited.dm`

2023-07-21 20:26 UTC, Tsurupeta requested changes, later dismissed
^

2023-08-03 19:58 UTC, TheDarkElites approved these changes

2023-08-03 20:08 UTC, merged