Ports Jump Point Search pathfinding from TG (as well as supplementaries)
Foundation-19/Foundation-19 pull request #1219
Opened 2023-07-26 23:00 UTC by cheesePizza2

## About the Pull Request

Ports JPS pathfinding and supplementary code from TG. Requested by TheDarkElites.

## Why It's Good For The Game

[Summed up pretty nicely in the OG PR.](https://github.com/tgstation/tgstation/pull/56780)

## Changelog

:cl:
code: General TG optimized code ported.
refactor: AStar pathfinding changed to JPS pathfinding, which should work MUCH faster (and better and cleaner)
/:cl:

2023-07-27 01:13 UTC, TheDarkElites commented on code/__defines/_helpers.dm
put this in code/_helpers

2023-07-27 11:37 UTC, cheesePizza2 commented on code/__defines/_helpers.dm
no, these are defines, they stay in _defines (also i was having compiler errors when they WERE in _helpers)

2023-07-27 16:29 UTC, TheDarkElites commented on code/__defines/_helpers.dm
Wait no you're absolutely right.

Could you change the name of the file to like helper defines or something to avoid confusion?

2023-07-27 16:58 UTC, TheDarkElites requested changes

2023-07-27 16:58 UTC, TheDarkElites commented on code/__defines/subsystem-priority.dm
> +#define SS_PRIORITY_PATHFINDER    23
add appropriate comment to descibe this

2023-07-27 16:58 UTC, TheDarkElites commented on code/modules/SCP/SCPs/SCP-173.dm
> +	if(!target || !steps_to_target || !steps_to_target.len)
```suggestion
	if(!target || !LAZYLEN(steps_to_target)
```

2023-07-30 17:13 UTC, Tsurupeta commented
tests failing

2023-08-01 21:58 UTC, TheDarkElites requested changes

2023-08-01 21:58 UTC, TheDarkElites commented on code/__defines/SCP.dm
The entire is_scp012_affected proc is gone in the SCP refactor so you might just want to leave this file unchanged to avoid merge conflicts.

2023-08-01 21:58 UTC, TheDarkElites commented on code/modules/mob/mob_movement.dm
> -	if (mob.is_scp012_affected(n))
see previous.

2023-08-05 16:41 UTC, Tsurupeta approved these changes

2023-08-05 16:42 UTC, TheDarkElites approved these changes

2023-08-05 16:50 UTC, merged