Ports admin macros from TG
Foundation-19/Foundation-19 pull request #1224
Opened 2023-07-30 20:33 UTC by cheesePizza2

## About the Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-17 17:57 UTC, TheDarkElites requested changes
can you also go through and implement the macros in the code where needed? Thank you :)

2023-08-19 00:04 UTC, cheesePizza2 commented
> can you also go through and implement the macros in the code where needed? Thank you :)

done

2023-08-21 13:56 UTC, TheDarkElites submitted a review, later dismissed
Looks fine to me, will also ask Tsurpta to glance over it.

2023-08-21 17:17 UTC, Tsurupeta commented on code/modules/admin/topic.dm
> +		usr.client.holder.marked_datum_weak = weakref(datum_to_tag)
rename it from weak to ref........

2023-08-21 20:15 UTC, cheesePizza2 commented on code/modules/admin/topic.dm
> +		usr.client.holder.marked_datum_weak = weakref(datum_to_tag)
Done

2023-08-24 01:37 UTC, TheDarkElites submitted a review, later dismissed
It looks fine to me, and this has seemingly fixed Tsurpta's concern. Ill ask him for sure before we merge it but for tm this is fine.

2023-08-25 00:57 UTC, TheDarkElites approved these changes
last review is still good for this

2023-09-02 17:00 UTC, Tsurupeta approved these changes

2023-09-02 17:01 UTC, merged