Ports TG status effects + alerts + etc
Foundation-19/Foundation-19 pull request #1226
Opened 2023-08-03 14:23 UTC by cheesePizza2

## About the Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-20 21:29 UTC, TheDarkElites commented
Dont forget to clean out any old code that provides the same or similar functionality

2023-12-27 21:30 UTC, cheesePizza2 commented
ready for speedmerge with 0 testing

2023-12-29 23:26 UTC, Tsurupeta commented
fix your changelog my guy

2023-12-29 23:26 UTC, cheesePizza2 commented
> fix your changelog my guy

me after the lobotomy

2024-01-05 13:03 UTC, EgorDinamit commented on code/modules/mob/living/carbon/human/memetic_insulation.dm
> +	var/viewdistance = is_nearsighted_currently() ? 7 : 2 //cant read if you're nearsighted
This broke everything.
```suggestion
	var/viewdistance = is_nearsighted_currently() ? 2 : 7 //cant read if you're nearsighted
```

2024-01-05 13:05 UTC, EgorDinamit requested changes
This PR broke everything related to seeing &  hearing.
Fix it before TMing again.

2024-04-09 03:53 UTC, Tsurupeta requested changes

2024-04-09 03:53 UTC, Tsurupeta commented on code/modules/multiz/zmimic/mimic_movable.dm
> +				bound_overlay.setDir(dir)
yet again pizza proceeds to rename 1 proc for no reason and then change its name in 400 files

2024-04-09 03:55 UTC, Tsurupeta commented
also how about you split this shit, github doesnt even load files past ~half of this PR contents, I physically can't review unless I click "show file" on 250 files

2024-04-09 08:12 UTC, tichys commented
someday this will be done

2024-06-22 20:26 UTC, merged