Fixes armor shit
Foundation-19/Foundation-19 pull request #1251
Opened 2023-08-06 00:33 UTC by cheesePizza2

## About the Pull Request

How has no one noticed this

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-06 01:20 UTC, TheDarkElites submitted a review, later dismissed

2023-08-06 13:03 UTC, HaultyAnonie commented
I've seen some of the head-covers deleted, would this cause a problem in-game since I'm pretty sure the SAARE helmcover is mapped somewhere.

2023-08-07 19:42 UTC, Tsurupeta requested changes
check icon state of lcz comm vest to heavy-guard-armor

2023-08-08 06:05 UTC, cheesePizza2 commented
> change icon state of lcz comm vest to heavy-guard-armor

done

2023-08-11 18:39 UTC, Tsurupeta approved these changes

2023-08-11 18:40 UTC, TheDarkElites approved these changes

2023-08-11 18:40 UTC, merged