Adds automatic dir-facing on fire + a few balloon alerts + spellcheck
Foundation-19/Foundation-19 pull request #1302
Opened 2023-08-30 04:34 UTC by cheesePizza2

## About the Pull Request

Adds an OPTIONAL pref for automatically facing direction after firing a gun.

Also converts a few gun-related to_chats to balloon_alerts

Also also fixes a pref's spelling

## Why It's Good For The Game

The auto-facedir was suggested as a nice QoL feature, to make it easier to shoot while retreating.

## Changelog

:cl:
qol: New preference: "Auto-face direction after shooting". Now you can retreat while firing WITHOUT having to struggle with Bay controls!
qol: A few gun-related to_chats (on the sidebar) have been changed to balloon_alerts (right on top of the gun).
balance: rebalanced something
spellcheck: Fixes submit/cancel swap button typo.
/:cl:

2023-08-30 16:48 UTC, casualspacestation14enjoyer commented
closes #1303

2023-08-30 16:55 UTC, cheesePizza2 commented
> Contributor

No it doesn't

2023-08-31 05:56 UTC, DaGoonCore commented
There's an idea but Uh, could you tie it to harm intent rather than be specifically after a ranged weapon use?

2023-08-31 06:08 UTC, Tsurupeta commented
Just add the interface button to face dir

2023-08-31 18:59 UTC, TheDarkElites requested changes

2023-08-31 18:59 UTC, TheDarkElites commented on code/modules/projectiles/gun.dm
> +		balloon_alert(user, "can't fire!")
```suggestion
		balloon_alert(user, "can't fire yet!")
```

2023-09-01 03:40 UTC, cheesePizza2 commented
> Just add the interface button to face dir

out of scope

2023-09-01 09:44 UTC, Tsurupeta commented
> > Just add the interface button to face dir
> 
> out of scope

I don't like this PR, you're approaching problem from the wrong direction.

2023-09-01 19:39 UTC, cheesePizza2 commented
> > > Just add the interface button to face dir
> > 
> > 
> > out of scope
> 
> I don't like this PR, you're approaching problem from the wrong direction.

???? this isn't stopping us from adding a button for facing dir as well, it's just a clientside pref that some people might find useful.

2023-09-25 18:05 UTC, TheDarkElites approved these changes

2023-09-25 18:06 UTC, TheDarkElites commented
Despite Tsurpta's protests I think this PR is fine and the preference is optional so I dont see an issue.

2023-09-25 18:06 UTC, merged