APC improvements
Foundation-19/Foundation-19 pull request #1304
Opened 2023-08-30 05:30 UTC by cheesePizza2

## About the Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-09-14 20:42 UTC, Tsurupeta requested changes, later dismissed

2023-09-14 20:42 UTC, Tsurupeta commented on code/datums/wires/apc.dm
> +			addtimer(CALLBACK(A, /obj/machinery/power/apc.proc/reset_wire, wire), 30 SECONDS)
.proc????

2023-09-14 20:42 UTC, Tsurupeta commented on code/datums/wires/apc.dm
> +				addtimer(CALLBACK(A, /obj/machinery/power/apc.proc/reset_wire, wire), 120 SECONDS)
.proc?????

2023-09-14 20:42 UTC, Tsurupeta commented on code/datums/wires/apc.dm
> +				addtimer(CALLBACK(A, /obj/machinery/power/apc.proc/reset_wire, wire), 1 SECOND)
???

2023-09-15 00:38 UTC, cheesePizza2 commented on code/datums/wires/apc.dm
> +			addtimer(CALLBACK(A, /obj/machinery/power/apc.proc/reset_wire, wire), 30 SECONDS)
What's the issue here?

2023-12-22 16:32 UTC, EgorDinamit approved these changes
Let's merge it!

2023-12-22 16:38 UTC, merged