LCZ Division Adjustments
Foundation-19/Foundation-19 pull request #1570
Opened 2024-03-24 20:47 UTC by ChromeFoxxity

## About the Pull Request

Adds one more LCZ Division, the Recontainment Unit. Also adjusts the loot of said divisions.

## Why It's Good For The Game

Adds different gameplay, some are unarmored, some are slower. Some also then have different jobs.

## Changelog

:cl:
add: Adds headsets to make communcations easier, adds new armor, adds Recontainment unit room, adds Combat Medic medkits, adds Riot Control metal shields. 
fix: Fixed heavy revolver.
/:cl:

![image](https://github.com/Foundation-19/Foundation-19/assets/114542226/01218e4a-fd74-41c4-afef-2aec537cb165)
![image](https://github.com/Foundation-19/Foundation-19/assets/114542226/ba70de4a-4950-4f35-a416-9d78f9e51f26)
![image](https://github.com/Foundation-19/Foundation-19/assets/114542226/29bb3090-f8dc-4fb1-b231-b55a0e9db9ea)
![image](https://github.com/Foundation-19/Foundation-19/assets/114542226/695c49d4-f08f-4133-a1a9-872a81b5359b)

2024-03-27 16:00 UTC, TheDarkElites requested changes

2024-03-27 16:00 UTC, TheDarkElites commented on code/game/jobs/job/security.dm
> +	requirements = list("LCZ Guard" = 480)
Revert this change

Likely caused by GitHub fuckery

2024-03-27 16:01 UTC, TheDarkElites commented on code/game/jobs/job/security.dm
> +	requirements = list("LCZ Guard" = 480)
Specifically the req change not alt titled

2024-04-02 19:47 UTC, TheDarkElites requested changes

2024-04-02 19:47 UTC, TheDarkElites commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/night/security
Sec shouldent have nvgs

2024-04-02 19:50 UTC, ChromeFoxxity commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/night/security
They are sechud nightvision goggles, I was gonna make them for OMEGA-1.

2024-04-03 17:33 UTC, K4rlox commented
lcz staff cannot get into their own division rooms, open their lockers or use their vendors

ex: response agent, cant enter response agent room or use the gear
combat medic: cant enter combat medic room
riot control: same as above

2024-04-03 18:02 UTC, ChromeFoxxity commented
> lcz staff cannot get into their own division rooms, open their lockers or use their vendors
> 
> ex: response agent, cant enter response agent room or use the gear

That was an accident, but it works due to the division being removed due to development staff wishing for such.

2024-04-04 02:25 UTC, bobjension commented
![scp5](https://github.com/Foundation-19/Foundation-19/assets/76455911/03f5eefd-4a48-43a4-801f-2d98fdae0650)
![scp4](https://github.com/Foundation-19/Foundation-19/assets/76455911/11bca1c7-afb7-433d-b57a-44062a5a6109)
![scp3](https://github.com/Foundation-19/Foundation-19/assets/76455911/1784fe93-4626-4bff-88f2-2d643ab10d7e)
![scp2](https://github.com/Foundation-19/Foundation-19/assets/76455911/7ab555b2-de5e-4163-8322-2d092896510b)
![scp1](https://github.com/Foundation-19/Foundation-19/assets/76455911/b6ca6c73-57f0-4bc5-aecd-92c63a982a92)
![scp](https://github.com/Foundation-19/Foundation-19/assets/76455911/a4fa1ca5-6934-47d5-ae56-7862c638be8b)
i don't intend for the coping to start in this comment section but i'll leave this here

2024-04-04 17:11 UTC, Ambrose997 commented
Not really sure why you blocked off the class D smelter when smelted ores have never been part of the reasons for escapes, at most they make baseball bats and are a nuisance to the guards. 

Also LCZ medical has no chem dispenser lmao. GL to the doctors relying on the shitty supply in the first aid kit storage and having to run to EZ to get important chems rather than being able to make the on-the-fly. I look forward to both the Class D and LCZ Guard mortality rate increasing after this.

There's other issues which actually make escape far easier than it was before, but for shits and giggles i'm gonna refrain from mentioning them and let this be apparent when it eventually happens lol.

2024-04-04 17:14 UTC, ChromeFoxxity commented
> Not really sure why you blocked off the class D smelter when smelted ores have never been part of the reasons for escapes, at most they make baseball bats and are a nuisance to the guards.
> 
> Also LCZ medical has no chem dispenser lmao. GL to the doctors relying on the shitty supply in the first aid kit storage and having to run to EZ to get important chems rather than being able to make the on-the-fly. I look forward to both the Class D and LCZ Guard mortality rate increasing after this.
> 
> There's other issues which actually make escape far easier than it was before, but for shits and giggles i'm gonna refrain from mentioning them and let this be apparent when it eventually happens lol.

Good for you, the chemistry lab is only a security precaution, and it isn't fully sealed off, it's still technically able to be broken into.

2024-04-04 17:23 UTC, Ambrose997 commented
The chemistry lab doesn't exist. I think you mean the smelter. 

And I think you underestimate how powerful spiders are on this code. The one present in the smelting area that is now walled off will fuck up anyone who tries with ease.

2024-04-04 17:41 UTC, Ambrose997 commented
Secondly, i'm unsure of how you expect it to be broken into. It doesn't really matter how strong the wall is, pickaxes etc do not break walls down.

2024-04-04 17:44 UTC, Ambrose997 commented
Why was auto assignment removed out of curiosity? It made things mega convenient for D-Class.

2024-04-04 17:47 UTC, Ambrose997 commented
re-add mirrors too please. Mirror loot was great.

2024-04-04 18:51 UTC, Ambrose997 commented
Kitchen is missing a rolling pin.

2024-04-05 22:01 UTC, Ambrose997 commented
D-Class want their cigarettes/lighters back >:( 

Also stasis gens + wrenches

2024-04-07 19:00 UTC, quadbium commented
![court](https://github.com/Foundation-19/Foundation-19/assets/138327811/20c47f0e-3599-401e-b2cf-b53396defa55)
that courtroom has no witness stand

2024-04-07 19:01 UTC, ChromeFoxxity commented
> ![court](https://private-user-images.githubusercontent.com/138327811/320304969-20c47f0e-3599-401e-b2cf-b53396defa55.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTY3NTEsIm5iZiI6MTcxMjUxNjQ1MSwicGF0aCI6Ii8xMzgzMjc4MTEvMzIwMzA0OTY5LTIwYzQ3ZjBlLTM1OTktNDAxZS1iMmNmLWI1MzM5NmRlZmE1NS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxOTAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWQ0N2VmNWI0ZjIyOTFmMDA2M2MwZTU2NWFlYjIwMWNlYmQ2MzgxMTg3NGE2NmIxYmJhZTE4YjA2ZjJkMjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5VK02T8wDre7YSmziT3jrWRU2RNI6uB-d1J1MpAocuY) that courtroom has no witness stand

I'm pretty sure they could just use the normal stand, but fine.

2024-06-10 22:56 UTC, Ambrose997 commented
Can you cut it out with the fucking commit spam? 186 commits, 123 files changed, what the fuck? Leave my fucking inbox alone!

2024-06-10 23:05 UTC, WoodenTucker commented
whats a comment spam

2024-06-10 23:06 UTC, WoodenTucker commented
hi ambrose
![image](https://github.com/Foundation-19/Foundation-19/assets/77739066/b678316e-2fb7-4253-8228-8c100db1cb3f)

2024-06-10 23:12 UTC, ChromeFoxxity commented
> Can you cut it out with the fucking commit spam? 186 commits, 123 files changed, what the fuck? Leave my fucking inbox alone!

No.

2024-06-12 09:38 UTC, merged