Mounted flash wire cut indicator and sound
Foundation-19/Foundation-19 pull request #1622
Opened 2024-03-30 22:34 UTC by Saicchi

## About the Pull Request

Add visual indication that a flash has been disabled.

## Why It's Good For The Game

So players can know why a mounted flash is not working and how to fix it.

## Changelog

:cl:
add: wire cut indicators on mounted flash
/:cl:

2024-03-31 12:19 UTC, Tsurupeta requested changes
we have examine text override for that, you can't just edit item's desc

2024-03-31 19:17 UTC, Saicchi commented
Added to `examine`

2024-04-02 14:21 UTC, Tsurupeta approved these changes

2024-04-02 15:47 UTC, TheDarkElites commented
Will slot for tm when I get home

2024-04-05 09:16 UTC, merged