SCP - 5000 and Outfits
Foundation-19/Foundation-19 pull request #1628
Opened 2024-04-01 14:21 UTC by tichys

Its SCP - 5000 and its a fucking ninja suit, what do you want from me? a cookie?

2024-04-02 02:04 UTC, TheDarkElites commented
Im going to kill you you didn't even separate your thing to a different branch from the net changes

2024-04-02 02:04 UTC, TheDarkElites commented
AND HE TEST MERGED IT

2024-04-02 02:06 UTC, cheesePizza2 commented
> AND HE TEST MERGED IT

we truly live in a society

2024-04-02 09:03 UTC, tichys commented
> Im going to kill you you didn't even separate your thing to a different branch from the net changes

hope about you do that >:C... its a small change and one pr that i didnt make a new branch on

2024-04-02 19:42 UTC, TheDarkElites requested changes

2024-04-02 19:42 UTC, TheDarkElites commented on code/modules/clothing/spacesuits/rig/suits/light.dm
> +/obj/item/rig/light/stealth/scp5000
Doesn't properly initialize SCP datum

for shame lestat for shame

2024-04-02 19:42 UTC, TheDarkElites commented
pulling this off TM until it gets a proper review and and gets approved

2024-04-04 03:18 UTC, checkraisefold commented
>overwrote the rig module instead of making a subtype separate one

2024-04-04 03:20 UTC, checkraisefold commented on code/modules/clothing/spacesuits/rig/suits/light.dm
> +	req_access = list(ACCESS_SYNDICATE)
you dont need this here it is already inherited from the scp5000 type

2024-06-09 07:33 UTC, merged