[READY FOR INITIAL TM PERIOD] - SCP-939 additions
Foundation-19/Foundation-19 pull request #1642
Opened 2024-04-04 15:11 UTC by Yawet330

## About the Pull Request
Adds SCP-939, a persistent, dangerous packhunting species.

This is subject to heavy change and scrutiny.

## Why It's Good For The Game
Doggy :D

## Changelog

:cl:
add: SCP-939. In all of their horrific glory.
/:cl:

2024-04-04 15:28 UTC, TheDarkElites commented
This guys has not heard of draft prs apparently

2024-04-09 19:23 UTC, cheesePizza2 requested changes

2024-04-09 19:23 UTC, cheesePizza2 commented on code/game/objects/items/devices/boombox.dm
> +	desc = "A device used to emit rhythmic sounds, colloquialy refered to as a 'boombox'. It's in a retro style (massive), and absolutely unwieldy. This one seems broken."
??? why are you fucking with boomboxes? this should be a separate PR

2024-05-31 14:21 UTC, Vizoplez commented
This should be un-TM'd IMMEDIATELY....

I need to recode a lot of this.

2024-07-07 09:04 UTC, closed without merging