fixes hardsuit access requirements
Foundation-19/Foundation-19 pull request #1750
Opened 2024-07-10 20:37 UTC by quadbium

## About the Pull Request

fixes hardsuit access requirements
## Why It's Good For The Game
several hardsuits use unused access requirements, this fixes that

## Changelog

:cl:
balance: Changed the internal affairs hardsuit to admin 2
balance: Changed the toxins hardsuit to science 1
balance: Changed the medical hardsuit to medical 1
balance: removed access requirements from the working SCP-5000 hardsuit
/:cl:

2024-07-20 02:55 UTC, checkraisefold requested changes

2024-07-20 02:55 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-5000.dm
> +	req_access = list()
```suggestion
	req_access = list(ACCESS_ADMIN_LEVEL3)
```
or some other access level, even level 1

2024-07-22 05:12 UTC, checkraisefold approved these changes

2024-09-12 00:07 UTC, checkraisefold requested changes

2024-09-12 00:07 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-5000.dm
> +	req_access = list(ACCESS_ADMIN_LEVEL3)
```suggestion
	req_access = list(ACCESS_ADMIN_LVL3)
```

2024-09-12 00:07 UTC, checkraisefold approved these changes

2025-03-21 22:15 UTC, Tsurupeta approved these changes

2025-03-21 22:15 UTC, merged