Big Iron, pr idea from Gio
Foundation-19/Foundation-19 pull request #1752
Opened 2024-07-11 00:56 UTC by oprimeolt

## About the Pull Request

Renames mateba to the 'Big Iron'

## Why It's Good For The Game

It is not good for the game but not bad either

## Changelog

:cl:Oprime
add: Cool examine text by Gio
/:cl:

2024-07-11 14:43 UTC, projectkepler-ru reviewed
You can discard the variable if it's already a subtype of the mateba

2024-07-11 14:43 UTC, projectkepler-ru commented on maps/site53/items/guns.dm
> +	caliber = ".44"
You can discard this if it's already a subtype of the mateba

2024-07-11 14:43 UTC, projectkepler-ru commented on maps/site53/items/guns.dm
> +	fire_delay = 6
You can discard this if it's already a subtype of the mateba

2024-07-11 14:43 UTC, projectkepler-ru commented on maps/site53/items/guns.dm
> +	origin_tech = list(TECH_COMBAT = 2, TECH_MATERIAL = 2)
You can discard this if it's already a subtype of the mateba

2024-07-11 14:43 UTC, projectkepler-ru commented on maps/site53/items/guns.dm
> +	ammo_type = /obj/item/ammo_casing/pistol/a50
You can discard this if it's already a subtype of the mateba

2024-07-11 14:43 UTC, projectkepler-ru commented on maps/site53/items/guns.dm
> +	handle_casings = CYCLE_CASINGS
You can discard this if it's already a subtype of the mateba

2024-09-12 00:04 UTC, checkraisefold requested changes

2024-09-12 00:04 UTC, checkraisefold commented on maps/site53/items/guns.dm
> +	desc = "A Mateba Unica chambered in .44 Magnum, it has multiple engravings of fine art along it's barrel, on the right side a fine engraving reads 'I fought the law and the law won', while the left
```suggestion
	desc = "A Mateba Unica chambered in .44 Magnum. Various engravings of fine art adorn the sides of the barrel. On the right side, an engraving reads 'I fought the law and the law won'. A Security Department logo is precisely cut into the grip, with an engraved label of 'Marty Robbins' below it."
```
we dont need the notches reference to the song marty robbins is good enough

2024-09-12 00:04 UTC, checkraisefold commented on maps/site53/items/guns.dm
> +	handle_casings = CYCLE_CASINGS
```suggestion
```
inherited

2024-09-12 00:05 UTC, checkraisefold commented on maps/site53/items/guns.dm
> +
```suggestion
```

2024-09-12 00:06 UTC, checkraisefold approved these changes

2024-09-12 14:00 UTC, merged