SCP-458 PIZZA
Foundation-19/Foundation-19 pull request #1824
Opened 2024-10-11 13:55 UTC by K4rlox

## About the Pull Request

remake of https://github.com/Foundation-19/Foundation-19/pull/1783

Tg's pizza box code, chooses 1 pizza per ckey, always gives that spesific pizza everytime until round end

## Why It's Good For The Game

Pizza

## Changelog

:cl:
add: SCP-458 currently only admin spawn
/:cl:

2024-10-20 22:47 UTC, checkraisefold requested changes, later dismissed

2024-10-20 22:47 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-458.dm
> +		/obj/item/reagent_containers/food/snacks/sliceable/pizza/vegetablepizza = 0.8) //pizzas here are weighted by chance to be someone's favorite
```suggestion
	// Pizza types are weighted by their chance to be someone's favorite
	var/list/pizza_types = list(
		/obj/item/reagent_containers/food/snacks/sliceable/pizza/meatpizza = 1,
		/obj/item/reagent_containers/food/snacks/sliceable/pizza/mushroompizza = 1,
		/obj/item/reagent_containers/food/snacks/sliceable/pizza/margherita = 1,
		/obj/item/reagent_containers/food/snacks/sliceable/pizza/vegetablepizza = 0.8
	)
```

2024-10-20 22:47 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-458.dm
> +// Description when examined
```suggestion

// Description when examined
```

2024-10-20 22:47 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-458.dm
> +/obj/item/pizzabox/scp458/Initialize()
```suggestion

/obj/item/pizzabox/scp458/Initialize()
```

2024-10-20 22:47 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-458.dm
> +/obj/item/pizzabox/scp458/attack_self(mob/living/user)
```suggestion

/obj/item/pizzabox/scp458/attack_self(mob/living/user)
```

2024-10-20 22:47 UTC, checkraisefold commented on code/modules/SCP/SCPs/SCP-458.dm
> +/obj/item/pizzabox/scp458/proc/attune_pizza(mob/living/carbon/human/noms) //tonight on "proc names I never thought I'd type"
```suggestion

/obj/item/pizzabox/scp458/proc/attune_pizza(mob/living/carbon/human/noms)
```

2024-12-15 06:05 UTC, Tsurupeta approved these changes

2024-12-15 06:06 UTC, merged