GOC Updates (Large BUFF to GOC-ERT)
Foundation-19/Foundation-19 pull request #515
Opened 2022-07-21 18:31 UTC by AMcilraith

This makes the GOC more in line with their canon, giving them better armour and more weapons.

## About the Pull Request

Adds pulse rifles and hazard suits to the GOC Base.
Removes ballistic weapons from GOC Base.
Adds more grenades to GOC Base in the stead of ammo.
Adds a proper chem dispenser to the GOC Base.

## Why It's Good For The Game

It's good for the gsme because:
A) GOC is rarely used
B) GOC is now more in line with the canon

## Changelog

:cl:
add: pulse weapons in goc base
add: hardsuit in goc base
add: esword in goc base
add: ert chem dispenser in goc base
del: ballistics in goc base
balance: rebalanced goc, gives buffm makes more in line with canon

/:cl:

2022-07-22 00:48 UTC, Teragenic commented
Admin here. Firstly, there's the issue of that the armor is actually a downgrade from their normal armour, namely also that Hardsuits slow down the wearer.

Secondly, EMPs, and High-Yields are a bit iffy in the current balance of things because I'm pretty sure High Yields will break flooring AKA break mapping.

Thirdly, the doublestack pistols were removed due to them actually being bugged. Also they aren't Glock 19s, they are chambered in 10mm. They are Glock 20s.

Fourthly, the Military Rifle is a eh... Choice, it's 7mmR in Baycode. Won't be that bad compared to the 762-51 in our code. Still would prefer one type of ammo for it.

PS: We don't use GOC much because there's no reason to send it. Sending it usually results in the exact opposite reason they sent a Representative ICly.

Chem dispenser is a good change though 👍

2022-07-22 01:48 UTC, Vivalas commented
Isn't there also another PR which references PHYSICS operative that already has SAW/Grenade Launcher? Are there multiple GOC loadouts?

2022-07-22 01:54 UTC, Teragenic commented
On that comment. 

There is a different "Loadout" for admins to physically assign. It's not relevant for this PR though. But it exists already in game for Admins to give them a loadout, it's very old though... Doesn't even give them proper armor.

> Isn't there also another PR which references PHYSICS operative that already has SAW/Grenade Launcher? Are there multiple GOC loadouts?

2022-07-22 12:48 UTC, PrimeGenerations requested changes
Remove the hardsuits

2022-07-22 16:27 UTC, dawsonkeyes commented
> On that comment.
> 
> There is a different "Loadout" for admins to physically assign. It's not relevant for this PR though. But it exists already in game for Admins to give them a loadout, it's very old though... Doesn't even give them proper armor.
> 
> > Isn't there also another PR which references PHYSICS operative that already has SAW/Grenade Launcher? Are there multiple GOC loadouts?

the outfits aren't old, i'm just not a fan of the shoddy spriting on the goc-specific helmet and vest, so they get normal ones with a blue helmet cover and green ubac

2022-08-10 18:34 UTC, ItsVyzo commented
stale // no update

2022-08-10 18:34 UTC, closed without merging