Autoresponse addition
Foundation-19/Foundation-19 pull request #554
Opened 2022-07-24 12:26 UTC by Tsurupeta

Admins may now autorespond on ahelps and tickets.

## Changelog

:cl:
admin: added autoresponse to admin options
/:cl:

2022-07-25 01:35 UTC, Vivalas requested changes

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_IC_ISSUE "\blue <b>NOTICE: <font color=red>[usr.key]</font> is autoresponding with <font color='#009900'>'[choice]'</font>. This issue has been deemed an IC (In-Character)
guh, shouldn't you be using span classes here?

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_BECOMING_AN_SCP "\blue <b>NOTICE: <font color=red>[usr.key]</font> is autoresponding with <font color='#009900'>'[choice]'</font>. In order to become an SCP, the alert lev
is this a typo? becoming SCP is restricted to being above red? Or should it be below to prevent even more chaos?

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_D_CLASS_RIOT "\blue <b>NOTICE: <font color=red>[usr.key]</font> is autoresponding with <font color='#009900'>'[choice]'</font>. D-Class may only riot with permission from
Has this been changed? I thought it was 30 minutes and they don't need explicit permission

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_D_CLASS_CELLS "\blue <b>NOTICE: <font color=red>[usr.key]</font> is autoresponding with <font color='#009900'>'[choice]'</font>. You can only get out if the on-duty guards
lmao

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_DIRECTIONS_OR_LOST "\blue <b>NOTICE: <font color=red>[usr.key]</font> is autoresponding with <font color='#009900'>'[choice]'</font>. If you are lost, it is best to keep a
I feel like this should include a mentorhelp suggestion, since mentors can and should be helping with this sort of thing

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/topic.dm
> +		switch(choice)
this switch hurts a bit, especially with strings. could you datumize/#DEFINE these for maintainability and readability?

2022-07-25 01:35 UTC, Vivalas commented on code/modules/admin/topic.dm
> +		var/staff_message = "[usr.key] is autoresponding to [ref_client.key] with <font color='#009900'>'[choice]'</font>."
again, span classes. should probably re-use current ones or make new ones if really needed. warning/notice handle most of these cases

2022-07-27 19:11 UTC, Tsurupeta commented
Since all of the CLRF > LF stuff was fixed, now PR can be reviewed again.

2022-07-27 20:06 UTC, Penwin0 commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_THANKS "<b>Have a SCP day!</b>"
Might be better to #define and #undef in ticket.dm instead of them being global

2022-07-29 19:45 UTC, Tsurupeta commented on code/modules/admin/_defines.dm
> +#define TICKET_AUTORESPONSE_THANKS "<b>Have a SCP day!</b>"
Sure, I wanted it for a reason that no longer exists.

2022-07-30 06:08 UTC, merged