Access refactor v2
Foundation-19/Foundation-19 pull request #585
Opened 2022-07-30 03:39 UTC by HalfdeadKiller

## About the Pull Request

A very large edit of ID references, and job IDs. Almost every SS13 job has been commented out. Site 19 jobs have been moved from the maps folder to the game/code/ folder. Need to solve confusion with jobs being defined in two places though, with site53 taking priority when loading.

access_datum.dm has comments regarding access levels in general, and what I've cross-referenced with existing jobs.

I've done testing on the ID Computer, as I've edited stuff in card.dm, _access_defs.dm, access.dm. Everything seems to work, but there's no test like production.

PLEASE GO OVER MY CHANGES TO JOB ACCESS, AND SUGGEST CHANGES IF THINGS DON'T MAKE SENSE.

MAPS MAY NEED TO BE UPDATED. I WILL TRY TO UPDATE SOME THINGS IN MAPS AS I FIND THEM IN ANOTHER PR, IF OTHERS DO NOT GET TO IT.

## Why It's Good For The Game

Attempts to refactor and unify access levels in some way that makes sense.

## Changelog

:cl:
balance: Access Refactor v2
/:cl:

2022-07-30 13:28 UTC, Tsurupeta requested changes
Looked at 1/3 of it, and have problem with you assigning `DCLASS_KITCHEN` instead of regular kitchen for stuff. D-class shit should be completely separate from regular kitchens and stuff.

Gona review more later.

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/alarm.dm
> +	req_access = list(list(access_securitylvl1, access_engineeringlvl2, access_engineeringlvl2)) //access_securitylvl1 added since mapper air alarms have it configured.
```suggestion
	req_access = list(list(access_securitylvl1, access_engineeringlvl2)) //access_securitylvl1 added since mapper air alarms have it configured.
```

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/alarm.dm
> +	req_access = list(access_sciencelvl5, access_engineeringlvl2, access_engineeringlvl2)
```suggestion
	req_access = list(access_sciencelvl5, access_engineeringlvl2)
```

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/deployable.dm
>  	access_mime = 44
wtf is this, did you even read your changes or blindly CTRL+F replace everything and put out PR?

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/doors/firedoor.dm
> +	req_access = list(list(access_engineeringlvl2, access_engineeringlvl2))
```suggestion
	req_access = list(list(access_engineeringlvl2))
```

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/kitchen/gibber.dm
> +	req_access = list(access_dclasskitchen,access_medicallvl2)
```suggestion
	req_access = list(access_dclasskitchen, access_medicallvl2)
```

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/kitchen/gibber.dm
> +	req_access = list(access_dclasskitchen,access_medicallvl2)
though I dont remember if it requires BOTH of these accesses or only one, I think you need to reassess it.

2022-07-30 13:28 UTC, Tsurupeta commented on code/game/machinery/kitchen/smartfridge.dm
> +	req_access = list(list(access_medicallvl2,access_medicallvl2))
```suggestion
	req_access = list(list(access_medicallvl2))
```

2022-07-30 13:35 UTC, HalfdeadKiller commented on code/game/machinery/deployable.dm
>  	access_mime = 44
I read through everything it touched, decided if it was important or not, and then replaced all. I'd wager 80% of what has changed could actually be deleted, but I don't know if you all want a bunch of stuff deleted. That all appeared to be legacy ID stuff, commented out so people assigning access had an easier time adding every ID number together. None of it appears to be used.

2022-07-30 13:37 UTC, HalfdeadKiller commented on code/game/machinery/alarm.dm
> +	req_access = list(list(access_securitylvl1, access_engineeringlvl2, access_engineeringlvl2)) //access_securitylvl1 added since mapper air alarms have it configured.
Shit. I forgot that some items had multiple access, and when replacing it ended up putting the same one twice. Original access sheet didn't have kitchen defined, and comments said it was so the cooks could have access to D-Class stuff for training purposes. There isn't really an access level for civilian jobs, and in an effort to keep it not cluttered, I used existing D-Class access instead.

2022-07-30 13:51 UTC, HalfdeadKiller commented
Space Station 13 areas.dm needs access reviewed since I don't understand mapping code enough to understand the ramifications of areas having req_access = (%access%) defined.

2022-07-30 14:04 UTC, HalfdeadKiller commented
Investigate Accounts_DB.dm access requirements. Current code appears to want Adminlvl5 or access_finances. Originally I think it was access_captain and access_hop. This may want to be redefined to be only access_finances, but may require code logic changes.

2022-07-30 14:20 UTC, HalfdeadKiller commented on code/game/machinery/alarm.dm
> +	req_access = list(list(access_securitylvl1, access_engineeringlvl2, access_engineeringlvl2)) //access_securitylvl1 added since mapper air alarms have it configured.
Fixed in 995546f

2022-07-30 14:20 UTC, HalfdeadKiller commented on code/game/machinery/alarm.dm
> +	req_access = list(access_sciencelvl5, access_engineeringlvl2, access_engineeringlvl2)
Fixed in 995546f

2022-07-30 14:21 UTC, HalfdeadKiller commented on code/game/machinery/doors/firedoor.dm
> +	req_access = list(list(access_engineeringlvl2, access_engineeringlvl2))
Fixed in 995546f

2022-07-30 22:02 UTC, HalfdeadKiller commented
access_maint_tunnels needs some form of discussion on, since I'm not sure if mappers want to add it to maintenance doors or not. Some jobs I added it to, but it may need to be removed from some, depending on how access to doors is setup.

2022-07-31 10:14 UTC, Tsurupeta commented on code/game/machinery/deployable.dm
>  	access_mime = 44
![image](https://user-images.githubusercontent.com/41485301/182021510-2ea53b3e-06ba-4c4f-a35b-9406cda96c20.png)
`I've read everything` moment

2022-07-31 18:28 UTC, HalfdeadKiller commented on code/game/machinery/deployable.dm
>  	access_mime = 44
Would you rather I just delete all of the commented out stuff I replaced, which is what that stuff is in your picture?

2022-08-01 06:38 UTC, HalfdeadKiller commented
I need to go over the changes in code/game/jobs/job/ since I think I got confused and edited those when other ones needed to be edited instead. Those changes may be unnecessary.

2022-08-09 12:05 UTC, MixMashy reviewed
once-read-over for the duplicate of the access lines would be nice. No rush
As per
code/game/machinery/deployable.dm

2022-08-14 20:17 UTC, harryob commented
hey @halfdeadkiller, are you planning on deconflicting this pr? no worries if not, just give us a shout

2022-08-15 23:00 UTC, ivanmixo commented
If this isn't alive I'm murdering it in a couple days

2022-08-17 09:59 UTC, harryob commented
rip... thank you for the effort making the pr, though

2022-08-17 09:59 UTC, closed without merging