HRO Title: Head Auditor
Foundation-19/Foundation-19 pull request #654
Opened 2022-08-08 11:59 UTC by projectkepler-ru

## About the Pull Request

Alt Title for HRO: Head Auditor. this also give them a new 9mm revolver, the Rhino. alongside the detective outfit to go with
## Why It's Good For The Game

SD shouldn't be half arsed to go everywhere himself when he has his trust-worthy officer to investigate into all the issues
## Changelog

:cl:
add: Added new title + gun + outfit, Head Auditor
imageadd: added some icons and images
/:cl:

2022-08-08 12:04 UTC, harryob commented on maps/site53/job/outfits.dm
> +	gloves = /obj/item/clothing/gloves/forenic
```suggestion
	gloves = /obj/item/clothing/gloves/forensic
```

2022-08-09 08:41 UTC, checkraisefold commented
having the HRO be the detective is kind of dumb, someone please just add a detective role

2022-08-10 01:12 UTC, ivanmixo requested changes

2022-08-10 01:12 UTC, ivanmixo commented on code/game/objects/items/weapons/storage/belt.dm
> +/obj/item/storage/belt/holster/security/fullrhino/New()
Could you do it in `Initialize()` instead? Be sure to do `. = ..()` though

2022-08-12 14:59 UTC, projectkepler-ru commented
> having the HRO be the detective is kind of dumb, someone please just add a detective role

invalid opinion but i changed anywy

2022-08-13 02:47 UTC, checkraisefold commented
![image](https://user-images.githubusercontent.com/19525688/184465598-e6f4b736-df25-426e-aa66-a7c4ed25f438.png)
![image](https://user-images.githubusercontent.com/19525688/184465603-4d19d84a-9c7a-450f-8bbc-3c3a735c2362.png)
fix this

2022-08-14 20:00 UTC, harryob commented
as above + conflicts

2022-08-16 05:25 UTC, harryob commented
messy pr, please re-open if still interested

2022-08-16 05:25 UTC, closed without merging