Small fixes, changes, etc.
Foundation-19/Foundation-19 pull request #657
Opened 2022-08-09 00:36 UTC by respiten

## About the Pull Request

- re-routes body disposal in the CDZ to the Re-Education Departures, replaces the 'body disposal' with a a food/snack vending machine and a table with donuts for guards to pass through.
- removes two random closets in the D-Class Shower areas
- adds three possible random contraband locations in mining ruins and adds some random tool placements in the mining area and mining ruins.
- removed ugly in-wall AED cabinets and replaced them with nanomed cabinets in the ULCZ
- expanded on atmosia in the CDZ, giving priority to cryo/spawn locations (yes, I left the shutoff valves where they were so you can still suffocate the whole prison.)
- added a electric stove to EZ (it was EZ, get the pun?)
- adds snack and cola machine to HCZ offices.
- adds a small 3x3 break room across from the offices in the LCZ (where is the water cooler at? how do I talk shit about rebecca if there ain't no damn water cooler)
- changes the windows for the GOI to be tintable, changes GOI access to adminlvl2 and gives goi adminlvl2 access.
- removed CHIEF_ENGINEER access as that isn't being used in our current codebase for the mapping and replaced it with ENGINEERING_LEVEL_5.
- adds logistics equipment to logistics (approved stamp, denied stamp, filing cabinet, paper shredder.) also fixes all approved stamps that were previously invisible.
- I forgot to hit save after making minor adjustments to the spawn location of the stamps.

## Why It's Good For The Game

Ninety nine percent of what was done here was requested in the #mapping or #mapping-suggestions discord channels.

## Changelog

:cl: Respiten
add: fixed approved-stamps being invisible.
add: chief-engineer access.
add: moved body disposal in the CDZ to re-education departures, added vending machines and logistics equipment.
add: added contraband spawn locations and other small improvements.
/:cl:

2022-08-09 13:17 UTC, hry-gh requested changes
map tester thinks you've got a stray cable, look at the check and fix, please!

2022-08-09 19:50 UTC, harryob requested changes
merge conflicts!! terrifying

2022-08-09 22:17 UTC, respiten commented
> merge conflicts!! terrifying

2022-08-09 22:17 UTC, closed without merging

2022-08-10 11:11 UTC, harryob commented
https://github.com/ParadiseSS13/Paradise/discussions/16402

2022-10-11 07:22 UTC, respiten commented
I’ll have it fixed by tonight, thank you for the quick reply Harry!

On Tue, Aug 9, 2022 at 8:17 AM harryob ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> map tester thinks you've got a stray cable, look at the check and fix,
> please!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Foundation-19/Foundation-19/pull/657#pullrequestreview-1066707570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2M4EOLXVGIKUMBMVHO2PITVYJK7BANCNFSM55654QWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>