Add Holopad on all maps
Foundation-19/Foundation-19 pull request #728
Opened 2022-08-19 00:32 UTC by Mihail-Zub

## About the Pull Request

added Holopads on all Site53 maps
Except CDZ.

Fix one camera in "General Purpose Testing Chamber"

## Why It's Good For The Game

AI now can use holopads and other personnel now can too.

## Changelog

:cl:
add: add Holopads
fix: Rotate camera
/:cl:

2022-08-19 17:19 UTC, projectkepler-ru commented
im gonna fucking cry if this get merged before my PR because then I'llbe in limbo for another week trying to finish my shit

2022-08-19 22:33 UTC, harryob requested changes
hey, all the placements look good - we were really missing them.

one thing: you've used pixel nudges in a couple places to move the holopad more centrally. it ends up being a little weird in game (the AI hologram still appears on the original tile), and messes with deconstruction - mind moving them back to the centre of the tile?

thanks for your work!

2022-08-19 23:05 UTC, Mihail-Zub commented
fixed
@harryob

2022-08-20 11:18 UTC, harryob approved these changes

2022-08-20 11:31 UTC, merged