BCCM (Name subject to change) alpha
Foundation-19/Foundation-19 pull request #767
Opened 2022-08-31 09:53 UTC by Tsurupeta

## About the Pull Request

Alpha version of BCCM (Name subject to change) - an ASN banning and VPN checking subsystem.
close #731 

## Why It's Good For The Game

Nuff said.

## Changelog

:cl:
config: added a BCCM value to config.
admin: Added BCCM for use by admins.
server: Added SQL migrations for BCCM functionality. 
/:cl:

2022-09-02 14:10 UTC, TheTitanicEngineer reviewed
I would recommend replacing sql_sanitize_text with a different filter. sql_sanitize_text is still vulnerable to injection(in case an administrative account got compromised) as it does not filter characters used for comment, does not oblige input to follow a certain pattern(vulnerable to bypasses) and is used in many different types of input, making the proc unsuitable for forcing input to follow formats.

2022-09-03 12:25 UTC, harryob commented
> I would recommend replacing sql_sanitize_text with a different filter. sql_sanitize_text is still vulnerable to injection(in case an administrative account got compromised) as it does not filter characters used for comment, does not oblige input to follow a certain pattern(vulnerable to bypasses) and is used in many different types of input, making the proc unsuitable for forcing input to follow formats.

i agree, getting droptable'd would be an annoying. need a filter that will properly filter IP/ASN input because getting SQL injected would be so embarrasing

2022-09-24 13:17 UTC, checkraisefold commented
apparently ss13 servers have yet to discover the industry standard of using prepared statements with SQL databases, yet this implementation is barely not vulnerable to being droptable'd for the sole fact that something somewhere doesn't accept single backslashes, otherwise sql injection would be possible
you can fuck up the query but not inject any meaningful SQL because theres no way to close the quotes

2022-10-31 08:38 UTC, Vizoplez commented
This seems plain bad. On further evaluation I see SEVERAL problems with current implementation, especially banned staff accounts. An automated client such as Calamari, Byondhook, ByondControl can all call the neccessary staff commands w/ args to mass-rangeban users in a way that'd require manual deletion if not a full rollback.

Also as said before, this is really dangerous to give to regular staff with just R_BAN, esp. as it can filter people on mobile data connections (and those using mobile data routers)

2022-10-31 10:31 UTC, Tsurupeta commented
Bruh you are wrong

2022-11-01 11:26 UTC, checkraisefold commented
i don't understand why this adds a trim_spaces proc that is used in one location, can be done in one line of code with replacetext, and only partially fixes one sql injection hole

2022-11-01 12:24 UTC, Vizoplez commented
> i don't understand why this adds a trim_spaces proc that is used in one location, can be done in one line of code with replacetext, and only partially fixes one sql injection hole
> 
> what I also don't understand is why sql_sanitize_text is being modified which could break other shit when you can instead make a new, safer sql sanitize text proc that can be used in future code or older code can be updated to use it and it is made sure that there are no bugs

literally this

imagine if someone tries to add a ban with a space in someones name!!
(it gets filtered and the ban doesnt work)

2022-11-01 13:39 UTC, Tsurupeta commented
> i don't understand why this adds a trim_spaces proc that is used in one location, can be done in one line of code with replacetext, and only partially fixes one sql injection hole

Obviously, because I need a proc that removes all spaces from text, like ckey(), but without other stuff from ckey().

2022-11-01 13:46 UTC, Tsurupeta commented
Ok, I don't give a fuck about SQL injections anymore. Other than that, I guess everything is finished for the most part. It has a funny bug with tgui that I don't know how to fix and this will be for @MACIEKBAKI to figure out.

2022-11-01 17:27 UTC, MACIEKBAKI requested changes

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	return msg
Don't overwrite message without including its prior contents here, also call parent proc
I don't know what that will break but i dont think any other subsystem does that
```suggestion
/datum/controller/subsystem/bccm/stat_entry(msg)
	. = ..("[msg][is_active? "ACTIVE" : "OFFLINE]")
```

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	var/list/client/postponed_client_queue = new
I'd much rather subsystem definitions be in `code/controllers/subsystems` for consistency

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	var/list/client/postponed_client_queue = new
basically move this file there frankly

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	return msg
you may also want to add something to stat for when the system is disabled

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	return is_active
```suggestion
	. = is_active
	if(.)
		return

	tgui_panel_asn_data = GetAsnBanlistDatabase()
	tgui_panel_wl_data = GetWhitelistDatabase()

	var/list/clients_to_check = postponed_client_queue.Copy()
	postponed_client_queue.Cut()
	for (var/client/C in clients_to_check)
		CollectClientData(C)
		HandleClientAccessCheck(C, postponed = TRUE)
		HandleASNbanCheck(C, postponed = TRUE)
		CHECK_TICK
```
this is just a "this looks prettier and should work the same" suggestion that you can frankly ignore but less indentation = prettier = more readable in my eyes

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	log_and_message_admins("The Database Error has occured. BCCM is disabled.")
```suggestion
	log_and_message_admins("A Database error has occured. BCCM is automatically disabled.")
```

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/bccm.dm
> +	log_and_message_admins("has [bccm_status ? "enabled" : "disabled"] the BCCM system!")
You might want to double check and make sure the client is an admin and can do this here

2022-11-01 17:27 UTC, MACIEKBAKI commented on code/modules/admin/bccm/tgui_asn.dm
> +		qdel(src) //For some unknown reason it refuses to update UI when it goes from 1 to 0 entries, so last item gets stuck. I can't fix it now, maybe later. ~Tsuru
I'll look into this when I've got time

2022-11-01 18:21 UTC, MACIEKBAKI approved these changes

2022-11-01 18:28 UTC, merged

2022-11-01 23:22 UTC, checkraisefold commented
watch the server get bricked on friday from the sql_sanitize_text global change