Planemasters + filters + VC
Foundation-19/Foundation-19 pull request #862
Opened 2022-11-08 17:56 UTC by Tsurupeta

## About the Pull Request

Adds planes. Adds filters framework for mobs and clients. Additionally, adds drop_shadow filter for object plane and blur filter for openspace planes. 

Also makes vision cone use alpha mask instead of client image deletion.

close #847

close #636 

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/41485301/200787605-986c7d5b-f736-44ad-ad17-87a1a4d2a737.png)
![image](https://user-images.githubusercontent.com/41485301/200787633-bb2c1731-6e46-4594-a5a3-b927ceef35d3.png)

![image](https://user-images.githubusercontent.com/41485301/200787655-27ded72f-b16a-414c-bd3c-d32e31f59b4c.png)
![image](https://user-images.githubusercontent.com/41485301/200787667-20fd2844-ed02-4ccf-916c-264f5df390e1.png)

![image](https://user-images.githubusercontent.com/41485301/200787704-ac05cc12-e8a9-4075-9572-36f3e6de84b0.png)
![image](https://user-images.githubusercontent.com/41485301/200787720-c0d77478-1f79-4b78-8477-43d2f5e2fc15.png)

</details>

## Why It's Good For The Game

Fixes most of Vision Cone issues and also makes everything look better with shadows.

## Changelog

:cl:
add: Added openspace blur effetcs.
add: Added effect that draws shadows from objects.
fix: Rewrote Vision Cone to use alpha filter masks.
/:cl:

2022-11-09 11:23 UTC, checkraisefold commented
playtest looked good but havent reviewed code

2022-11-09 20:40 UTC, ivanmixo requested changes

2022-11-09 20:40 UTC, ivanmixo commented on code/_onclick/hud/human.dm
> +	..()
Calling parent twice?

2022-11-09 20:40 UTC, ivanmixo commented on code/modules/mob/living/carbon/human/vision_cone.dm
> +// "Otuska is a faggot"
```suggestion
// "Otuska is a faggot"
```
Github will probably bitch about this word, I'd refrain because codebase might be nuked for it

2022-11-09 20:40 UTC, ivanmixo commented on code/_onclick/hud/hud.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-11-09 20:40 UTC, ivanmixo commented on code/__defines/_planes+layers.dm
> +/obj/screen/plane_master/vision_cone/
Having it just defined with nothing like this isn't absolutely necesarry, but if you gotta 

```suggestion
/obj/screen/plane_master/vision_cone
```

2022-11-09 20:40 UTC, ivanmixo commented on code/__defines/_planes+layers.dm
> +/obj/screen/plane_master/vision_cone/primary/New() //For when you want things to not appear under the blind section.
Also any particular reasons these are done with `New()` and not `Initialize()`?

2022-11-09 22:20 UTC, checkraisefold commented on code/modules/mob/living/carbon/human/vision_cone.dm
> +// "Otuska is a faggot"
if you leave it in the repo will get banned, definitely remove this

2022-11-09 22:24 UTC, Tsurupeta commented on code/modules/mob/living/carbon/human/vision_cone.dm
> +// "Otuska is a faggot"
I'll think about something that I can replace that word with.

2022-11-09 22:36 UTC, CristoMagisto commented on code/modules/mob/living/carbon/human/vision_cone.dm
> +// "Otuska is a faggot"
"Pedicabere, Otsuka."

Roughly translates to: "you will be buggered, Otsuka."

2022-11-10 15:46 UTC, ivanmixo approved these changes

2022-11-10 17:49 UTC, merged

2022-11-10 21:18 UTC, Texicos commented
Quick question to any codemaniac, how would this have solved 999 going to nullspace when he tried healing a dead body, of which the mind would be in nullspace and 999 would follow it there.

2022-11-11 09:06 UTC, Tsurupeta commented
> Quick question to any codemaniac, how would this have solved 999 going to nullspace when he tried healing a dead body, of which the mind would be in nullspace and 999 would follow it there.
> 
> edit: 999 would follow the parent mind of the mob to nullspace since it was dead and 999 apparently attaches to minds not mobs. Just asking incase they closed the wrong bug report.

![image](https://user-images.githubusercontent.com/41485301/201305645-22abde87-fab7-457e-91bf-155cc0e0d318.png)