Rig fixes
Foundation-19/Foundation-19 pull request #893
Opened 2022-11-17 04:39 UTC by checkraisefold

## About the Pull Request

what it says on the tin
tested and working
closes #655 

## Why It's Good For The Game

emps bricking rigs was stupid as fuck and probably unintentional, and the tab not being there was straight up a bug with tgui port

## Changelog

:cl:
fix: Rigs are no longer bricked if they're EMPed while turned off.
fix: Hardsuit verbs tab shows up upon putting on a rig without having to refresh tgui.
/:cl:

the method for adding tabs/verbs to the statpanel properly is from the verb helpers in https://github.com/Foundation-19/Foundation-19/blob/dev/code/_helpers/verbs.dm, let me know if you want me to make a new helper for adding verbs to the statpanel without adding them to mob/client verbs since they're already verbs of the object, because people did NOT know the right way in #655

2022-11-20 14:21 UTC, MACIEKBAKI approved these changes

2022-11-25 16:53 UTC, ivanmixo requested changes

2022-11-25 16:53 UTC, ivanmixo commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		if(M.client)
Early returns

2022-11-25 16:53 UTC, ivanmixo commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	if(user.client)
Early returns

2022-11-28 04:13 UTC, checkraisefold commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		if(M.client)
fixed you picky fuck

2022-11-28 04:14 UTC, checkraisefold commented
ready to merge

2022-11-29 15:53 UTC, ivanmixo approved these changes

2022-11-29 15:53 UTC, merged