Pataphysical Incursion (New Event and 2 Antags)
Foundation-19/Foundation-19 pull request #912
Opened 2022-11-25 00:49 UTC by AndJusticeForAll0

## About the Pull Request

Adds a new random event called "Pataphysical Incursion" that chooses from a pool of 2 (with more to come) antagonistics that rely on Pataphysics. These antags are Murphy Law (SCP-3143), a sterotypical film noir detective, and Don Quixote (SCP-4028),, a famous character in literature. 
## Why It's Good For The Game

More random events are always good, and this one also adds a few new SCPs to the mix.
## Changelog

:cl:
add: Added Pataphysical Incursion event
add: Added Don Quixote and Murphy Law

/:cl:

2022-11-25 01:13 UTC, AndJusticeForAll0 commented
Potentially game breaking event chances were also changed

2022-11-25 02:23 UTC, AndJusticeForAll0 commented
Shark Punching Centre Operative has also been added as another possible event option.

2022-11-25 03:46 UTC, AndJusticeForAll0 commented
Events were also enabled because they weren't initially.

2022-11-25 16:56 UTC, MACIEKBAKI requested changes, later dismissed

2022-11-25 16:56 UTC, MACIEKBAKI commented on code/modules/events/event_container.dm
> +		new /datum/event_meta(EVENT_LEVEL_MODERATE, "Grid Check",							/datum/event/grid_check, 				0,		list(ASSIGNMENT_ENGINEER = 15, ASSIGNMENT_ANY = 5)),
you ought to note changes like you made in this file in the PR desc

2022-11-25 16:57 UTC, MACIEKBAKI commented
please also add to the pr desc what map changes you've made, i'm too lazy to review that

2022-11-25 16:58 UTC, MACIEKBAKI commented
also fix up this space tile
![image](https://user-images.githubusercontent.com/41126266/204029648-86e988c6-3cb3-4e96-9998-4d3a85ea17d8.png)

2022-11-25 16:59 UTC, MACIEKBAKI commented
overall, pretty nice PR, save for those few small details

2022-11-25 17:08 UTC, ivanmixo requested changes

2022-11-25 17:08 UTC, ivanmixo commented on code/game/antagonist/outsider/donquixote.dm
> +	return
Pointless return. Remove it on this and all the other ones. I know the others do it like this but they're shitty and should be addressed too.

2022-11-25 17:08 UTC, ivanmixo commented on code/game/objects/items/weapons/cards_ids.dm
> +/obj/item/card/id/murphylaw/New()
Use `Initialize()`, not `New()`. Also `return ..()` 2 lines down.

2022-11-25 17:08 UTC, ivanmixo commented on code/modules/events/pataphysics.dm
> +	if(valid_types.len)
```suggestion
	if(length(valid_types))
```

2022-11-25 17:08 UTC, ivanmixo commented on code/game/antagonist/outsider/donquixote.dm
> +
Remove this space too, guh.

2022-11-25 21:22 UTC, AndJusticeForAll0 commented
All issues have been fixed.

2022-11-26 00:58 UTC, ivanmixo requested changes, later dismissed
Code side okay, head map guy needs to see map changes.

2022-11-26 00:58 UTC, ivanmixo commented on code/game/antagonist/outsider/murphylaw.dm
> +
These too.
```suggestion
```

2022-11-26 00:58 UTC, ivanmixo commented on code/game/antagonist/outsider/sharkpunchingcentre.dm
> +
```suggestion
```

2022-11-30 21:48 UTC, harryob approved these changes
mapping

2022-11-30 22:36 UTC, ivanmixo submitted a review, later dismissed
The reviews were *not* stale, actually.

2022-12-08 15:30 UTC, Tsurupeta requested changes
It doesn't even work

2023-02-12 17:46 UTC, cheesePizza2 commented
reminder that nobody can make any changes to the event system while this is open (at least without major merge conflict headaches)

2023-02-14 16:15 UTC, Tsurupeta commented
It's not like it's getting fixed anytime soon. Closing due to being stale.

2023-02-14 16:15 UTC, closed without merging