Bullet Change 2: Blood Boogaloo.
Foundation-19/Foundation-19 pull request #960
Opened 2023-02-02 15:17 UTC by Yawet330

## About the Pull Request
TM this PR or the other one. This WILL change gameplay massively, making hypovolemic shock a VERY fast killer.

## Why It's Good For The Game
El balance test.

## Changelog

:cl:
balance: Blood/Bleed changes, heart-rate affects bleeding, arterial bleed buffs, hit-chance changes + nerfs in some areas. This is experimental and will be subject to change.
/:cl:

2023-02-02 15:20 UTC, Tsurupeta commented on code/modules/organs/external/_external.dm
> +	var/amputation_point               // Descriptive	string used in amputation.
```suggestion
	var/amputation_point               // Descriptive string used in amputation.
```

2023-02-02 15:21 UTC, Vizoplez commented on code/modules/organs/internal/heart.dm
> +	return "pacemaker-assisted [name]"
tbh i didnt even change this.

Thanks git

2023-02-02 15:21 UTC, Vizoplez commented on code/game/machinery/vitals_monitor.dm
> +					alerts[PULSE_ALERT] = "Heart-rate exceeding 250BPM, Possible Shock Detected! Patient Expiry likely!"
These changes tell people a better idea on how not to kill their patient

2023-02-02 15:25 UTC, Tsurupeta commented on code/modules/organs/internal/heart.dm
> +	return "pacemaker-assisted [name]"
It's eof newline

2023-02-02 15:34 UTC, aidan-bowman commented
At first glance, I'd say that the vitals monitor changes (i.e. the small descriptions of what's wrong with someone) are irrelevant to the bleeding changes, and as such should be pushed regardless of the rest of the PR (unless of course these descriptions only make sense with the new bleeding values).

2023-02-02 15:40 UTC, Tsurupeta approved these changes

2023-02-02 15:43 UTC, Tsurupeta requested changes

2023-02-02 15:43 UTC, Tsurupeta commented on code/game/machinery/vitals_monitor.dm
> +				alerts[LUNGS_ALERT] = "Abnormality in patient breathing detected!"
```suggestion
				alerts[LUNGS_ALERT] = "Abnormality in patient's breathing detected!"
```

2023-02-02 15:43 UTC, Tsurupeta commented on code/modules/mob/mob_helpers.dm
> +	BP_R_FOOT = 45, //Ditto
```suggestion
	BP_HEAD =   65,
	BP_CHEST =  5,
	BP_GROIN =  25,
	BP_L_ARM =  35,
	BP_R_ARM =  35,
	BP_L_HAND = 50,
	BP_R_HAND = 50,
	BP_L_LEG =  30,
	BP_R_LEG =  30,
	BP_L_FOOT = 45,
	BP_R_FOOT = 45,
```

2023-02-02 15:43 UTC, Tsurupeta commented on code/modules/mob/mob_helpers.dm
> +	BP_GROIN =  40, //This is pretty big, should be higher.
```suggestion
	BP_HEAD =   20,
	BP_CHEST =  85,
	BP_GROIN =  40,
```

2023-02-02 15:43 UTC, Tsurupeta commented on code/modules/mob/mob_helpers.dm
> +	BP_L_LEG =  25, //Legs, while a moving target, are pretty big. This stays the same.
```suggestion
	BP_L_HAND = 5,
	BP_R_HAND = 5,
	BP_L_LEG =  25,
```

2023-02-02 15:43 UTC, Tsurupeta commented on code/modules/mob/mob_helpers.dm
> +	BP_R_FOOT = 5,
```suggestion
	BP_L_FOOT = 5,
	BP_R_FOOT = 5
```

2023-02-02 15:55 UTC, cheesePizza2 commented
> balance: Blood + Hitchance.

DEFINITELY should make this more descriptive, holy shit.

2023-02-02 15:55 UTC, Vizoplez commented
> At first glance, I'd say that the vitals monitor changes (i.e. the small descriptions of what's wrong with someone) are irrelevant to the bleeding changes, and as such should be pushed regardless of the rest of the PR (unless of course these descriptions only make sense with the new bleeding values).

They do. This changes how heartrate scales bleeding, and bleeding overall. These give pretty good IC warnings on how you should treat an injured individual (sedation/painkillers/lowering heartrate/repairing brain)

2023-02-02 15:58 UTC, cheesePizza2 commented
> > At first glance, I'd say that the vitals monitor changes (i.e. the small descriptions of what's wrong with someone) are irrelevant to the bleeding changes, and as such should be pushed regardless of the rest of the PR (unless of course these descriptions only make sense with the new bleeding values).
> 
> They do. This changes how heartrate scales bleeding, and bleeding overall. These give pretty good IC warnings on how you should treat an injured individual (sedation/painkillers/lowering heartrate/repairing brain)

Fair enough, although if the PR gets closed it would still be a good idea for a different PR changing just the messages. From the looks of it though, I doubt this is getting closed.

2023-02-08 17:20 UTC, Tsurupeta approved these changes

2023-02-08 17:21 UTC, merged